console.log('🔧 DEBUGGING TOKEN ISSUE');
console.log('Ejecuta estos comandos en la consola del navegador después del login:');
console.log('');
console.log('1. Verificar tokens almacenados:');
console.log('console.log("auth_token:", localStorage.getItem("auth_token"))');
console.log('console.log("empleado_token:", localStorage.getItem("empleado_token"))');
console.log('');
console.log('2. Verificar instancia EmpleadoSystem:');
console.log('console.log("EmpleadoSystem token:", window.empleadoSys?.token)');
console.log('');
console.log('3. Verificar API client:');
console.log('console.log("API client token:", window.api?.token)');
console.log('');
console.log('4. Intentar login manual:');
console.log('fetch("/api/auth/login/empleado", {');
console.log('  method: "POST",');
console.log('  headers: {"Content-Type": "application/json"},');
console.log('  body: JSON.stringify({rut: "18.208.947-8"})');
console.log('}).then(r => r.json()).then(d => console.log("Login result:", d))');
console.log('');
console.log('5. Si el token parece correcto, verificar longitud:');
console.log('const token = localStorage.getItem("auth_token")');
console.log('console.log("Token length:", token?.length)');
console.log('console.log("Token starts with:", token?.substring(0, 10))');
console.log('console.log("Token ends with:", token?.substring(token.length - 10))');